version: '3'
services:
  web:
    build: .
    ports:
     - "8090:8090"
    depends_on:
      - "nginx"

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    environment:
      - PARAM=something
